### PR TITLE
Display resources based on URL query.

### PR DESCRIPTION
**Pull request by LamboCreeper**
Displays resources based on a given `?category`. This allows us to create a command for the bot that gives a link to only a specific category of resources.

### CODE REVIEW

**Comment by LamboCreeper** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/helpers/getQueries.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codesupport/website-frontend/pullRequest?prid=4936743&bid=16324795)

**Comment by LamboCreeper** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/helpers/getQueries.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codesupport/website-frontend/pullRequest?prid=4936743&bid=16324795)

**Comment by LamboCreeper** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/helpers/getQueries.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codesupport/website-frontend/pullRequest?prid=4936743&bid=16324795)

**Review by Jason2605 — APPROVED** [review]
Tested and works well.

**Pull request merged**
